/* GENERATED by scripts/build-icons.mjs from ./svg + ./manifest.json. Do not edit. */

import {
  ChevronIcon,
  ChainIcon,
  GridIcon,
  LineChartIcon,
  CubeIcon,
  LayersIcon,
  BlockchainIcon,
  FolderOpenIcon,
  DataSourcesIcon,
  AiAgentsIcon,
  WindowFormatIcon,
  AttachmentIcon,
  GithubIcon,
  OpenBookIcon,
  LogoBetaIcon
} from './generated'

/** Every icon, for gallery and story enumeration. */
export const ICONS = {
  ChevronIcon,
  ChainIcon,
  GridIcon,
  LineChartIcon,
  CubeIcon,
  LayersIcon,
  BlockchainIcon,
  FolderOpenIcon,
  DataSourcesIcon,
  AiAgentsIcon,
  WindowFormatIcon,
  AttachmentIcon,
  GithubIcon,
  OpenBookIcon,
  LogoBetaIcon
} as const

export type IconName = keyof typeof ICONS
