import { mkdtempSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import type { EngineState } from '@shared/ipc'

const userData = mkdtempSync(join(tmpdir(), 'beacon-provenance-'))

vi.mock('electron', () => ({ app: { getPath: () => userData } }))

const { readProvenance, writeProvenance } = await import('../dataSettings')
const { Engine } = await import('./engine')
const { generateArgs } = await import('./synthetic')

const MARKER = join(userData, 'store-provenance.json')

/** A server that only ever answers /health, which is the attach path. */
function health(version: string): typeof fetch {
  return (() =>
    Promise.resolve({
      ok: true,
      status: 200,
      json: () => Promise.resolve({ status: 'ok', version })
    })) as unknown as typeof fetch
}

/**
 * Read the state after the first health poll, which is where staleness is
 * decided. `start` polls immediately; the answer is a resolved promise away.
 */
async function connectedState(version: string): Promise<EngineState> {
  const engine = new Engine({ serverUrl: 'http://127.0.0.1:1', fetchImpl: health(version) })
  engine.start()
  await vi.waitFor(() => {
    expect(engine.getState().status).toBe('connected')
  })
  const state = engine.getState()
  engine.stop()
  return state
}

beforeEach(() => {
  writeFileSync(MARKER, '', 'utf-8')
  delete process.env.BEACON_DATA_PATH
})

afterEach(() => {
  vi.unstubAllEnvs()
})

describe('the store marker', () => {
  it('round-trips what was generated', () => {
    writeProvenance({ engineVersion: '0.6.0', args: ['-m', 'x'], generatedAt: 'then' })
    expect(readProvenance()).toEqual({
      engineVersion: '0.6.0',
      args: ['-m', 'x'],
      generatedAt: 'then'
    })
  })

  it('reads a damaged file as no marker rather than throwing', () => {
    // Half-written by a killed process, or hand-edited. Either way the app
    // has to start, and "no marker" is the safe reading: it offers nothing.
    writeFileSync(MARKER, '{"engineVersion"', 'utf-8')
    expect(readProvenance()).toBeUndefined()
  })
})

describe('what the engine says about the store on connect', () => {
  it('offers nothing when there is no marker, because the store is not ours', async () => {
    writeFileSync(MARKER, 'not json at all', 'utf-8')
    expect((await connectedState('0.7.0')).stale).toBeUndefined()
  })

  it('reports a store generated by an older py-beacon', async () => {
    writeProvenance({ engineVersion: '0.6.0', args: generateArgs(), generatedAt: 'then' })
    expect((await connectedState('0.7.0')).stale).toContain('0.6.0')
  })

  it('says nothing about a store that matches this build', async () => {
    writeProvenance({ engineVersion: '0.7.0', args: generateArgs(), generatedAt: 'then' })
    expect((await connectedState('0.7.0')).stale).toBeUndefined()
  })

  it('leaves a store named by BEACON_DATA_PATH alone, marker or not', async () => {
    // The strongest signal that the data is the user's. No offer, no matter
    // what a marker left behind by an earlier run happens to say.
    writeProvenance({ engineVersion: '0.6.0', args: generateArgs(), generatedAt: 'then' })
    vi.stubEnv('BEACON_DATA_PATH', 'D:/mine')
    expect((await connectedState('0.7.0')).stale).toBeUndefined()
  })
})
