// Copy the bundled webfonts out of their packages and into the renderer.
//
// The files are committed rather than imported from node_modules so the CSS
// can reference them with a plain relative url() that vite fingerprints — and
// so that what ships is visible in a diff. `pnpm run fonts:check` fails if the
// committed copies drift from the installed packages.
//
//   node scripts/build-fonts.mjs

import { copyFile, mkdir, readdir, rm, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(fileURLToPath(import.meta.url), '..', '..')
const OUT = join(ROOT, 'src', 'renderer', 'src', 'assets', 'fonts')
const MODULES = join(ROOT, 'node_modules', '@fontsource')

/**
 * Only the faces actually used, latin only.
 *
 * Inter ships 18 weights across a dozen subsets and Source Serif Pro nearly
 * as many; shipping all of them would be tens of megabytes for four faces
 * the design uses. Adding a weight here is deliberate, and shows up as a new
 * binary in the diff.
 */
const FACES = [
  { package: 'inter', file: 'inter-latin-400-normal.woff2' },
  { package: 'inter', file: 'inter-latin-500-normal.woff2' },
  // Real italics. Without them the browser slants the upright face, which is
  // not the same shape — Inter's italic is redrawn, not sheared. The footer's
  // version line has been faking it since BU-14; the Home date and title
  // (BU-54) made it worth fixing.
  { package: 'inter', file: 'inter-latin-400-italic.woff2' },
  { package: 'source-serif-pro', file: 'source-serif-pro-latin-400-italic.woff2' },
  { package: 'source-serif-pro', file: 'source-serif-pro-latin-600-italic.woff2' },
  // The menu bar only (Figma 81:2 specifies Roboto there, not Inter). Bundled
  // for the same reason as the others: it is on some machines and not others,
  // and the fallback is 5% wider — see BU-52.
  { package: 'roboto', file: 'roboto-latin-400-normal.woff2' }
]

const LICENCES = [
  { package: 'inter', to: 'Inter-OFL.txt' },
  { package: 'source-serif-pro', to: 'SourceSerifPro-OFL.txt' },
  { package: 'roboto', to: 'Roboto-Apache-2.0.txt' }
]

async function version(name) {
  const path = join(MODULES, name, 'package.json')
  const { default: meta } = await import(`file://${path}`, { with: { type: 'json' } })
  return { version: meta.version, license: meta.license }
}

async function main() {
  await rm(OUT, { recursive: true, force: true })
  await mkdir(OUT, { recursive: true })

  for (const face of FACES) {
    await copyFile(join(MODULES, face.package, 'files', face.file), join(OUT, face.file))
  }

  for (const licence of LICENCES) {
    await copyFile(join(MODULES, licence.package, 'LICENSE'), join(OUT, licence.to))
  }

  const inter = await version('inter')
  const serif = await version('source-serif-pro')
  const roboto = await version('roboto')

  // Provenance beside the binaries. A woff2 in a repo with no note saying
  // where it came from or what licence it carries is a liability.
  await writeFile(
    join(OUT, 'NOTICE.txt'),
    [
      'Fonts bundled with Beacon.',
      '',
      'Generated by scripts/build-fonts.mjs — do not edit by hand.',
      '',
      `Inter ${inter.version} (${inter.license}) — @fontsource/inter`,
      '  https://github.com/rsms/inter',
      `Source Serif Pro ${serif.version} (${serif.license}) — @fontsource/source-serif-pro`,
      '  https://github.com/adobe-fonts/source-serif',
      `Roboto ${roboto.version} (${roboto.license}) — @fontsource/roboto`,
      '  https://github.com/googlefonts/roboto',
      '',
      'Inter and Source Serif Pro are under the SIL Open Font License 1.1;',
      'Roboto is under the Apache License 2.0. All three permit redistribution',
      'as part of a bundled application. Full terms are in Inter-OFL.txt,',
      'SourceSerifPro-OFL.txt and Roboto-Apache-2.0.txt in this directory.',
      ''
    ].join('\n')
  )

  const files = await readdir(OUT)
  console.log(`[fonts] ${String(files.length)} files → ${OUT}`)
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error)
  process.exit(1)
})
