/**
 * Generates the token artefacts from tokens/colors.json.
 *
 *   src/renderer/src/tokens/tokens.css  CSS custom properties per data-theme
 *   src/renderer/src/tokens/tokens.ts   literals for chart code, which needs
 *                                       real values rather than var() strings
 *
 * Run with `pnpm run tokens:build`. CI runs `tokens:check`, which regenerates
 * and fails if the committed output drifts from the source.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SOURCE = join(root, 'tokens', 'colors.json')
const OUT_DIR = join(root, 'src', 'renderer', 'src', 'tokens')

const BANNER = `/* GENERATED by scripts/build-tokens.mjs from tokens/colors.json. Do not edit. */`

/** kebab-case token name -> camelCase TS identifier. */
function toCamel(name) {
  return name.replace(/-([a-z0-9])/g, (_, char) => char.toUpperCase())
}

/**
 * Figma exports translucent variables as 8-digit hex (e.g. surface is
 * #fbf3e233 — a wash over canvas, not an opaque fill). Rejecting those would
 * throw away the alpha and flatten washes into solid blocks.
 */
function assertValidHex(name, mode, value) {
  if (!/^#[0-9a-f]{6}([0-9a-f]{2})?$/i.test(value)) {
    throw new Error(`Token "${name}" mode "${mode}" is not a 6- or 8-digit hex colour: ${value}`)
  }
}

function readSource() {
  const source = JSON.parse(readFileSync(SOURCE, 'utf-8'))
  const { modes, tokens, raw } = source

  for (const [name, token] of Object.entries(tokens)) {
    for (const mode of modes) {
      if (!(mode in token)) throw new Error(`Token "${name}" is missing mode "${mode}"`)
      assertValidHex(name, mode, token[mode])
    }
  }
  return { modes, tokens, raw }
}

function buildCss({ modes, tokens }) {
  const blocks = modes.map((mode) => {
    const lines = Object.entries(tokens).map(([name, token]) => `  --${name}: ${token[mode]};`)
    return `:root[data-theme='${mode}'] {\n${lines.join('\n')}\n}`
  })

  // Unthemed html means an unstyled flash before the theme is applied, so the
  // light palette doubles as the bare :root fallback.
  const fallbackLines = Object.entries(tokens).map(
    ([name, token]) => `  --${name}: ${token[modes[0]]};`
  )
  const fallback = `:root {\n${fallbackLines.join('\n')}\n}`

  return `${BANNER}\n\n${fallback}\n\n${blocks.join('\n\n')}\n`
}

function buildTs({ modes, tokens, raw }) {
  const names = Object.keys(tokens)

  const nameUnion = names.map((name) => `  | '${name}'`).join('\n')

  const modeEntries = modes.map((mode) => {
    const lines = names.map((name) => `    '${name}': '${tokens[name][mode]}'`)
    return `  ${mode}: {\n${lines.join(',\n')}\n  }`
  })

  const rawEntries = Object.entries(raw)
    .filter(([key]) => key !== 'comment')
    .map(([key, value]) => `  ${toCamel(key)}: '${value}'`)

  return `${BANNER}

export type ThemeMode = ${modes.map((m) => `'${m}'`).join(' | ')}

export type ColorToken =
${nameUnion}

/**
 * Resolved literals per mode. Chart libraries paint to canvas and cannot read
 * CSS custom properties, so they need the value rather than a var() reference.
 * Components must use var(--token) instead of reaching in here.
 */
export const COLORS: Record<ThemeMode, Record<ColorToken, string>> = {
${modeEntries.join(',\n')}
}

/**
 * Mode-independent by approval (taxonomy 9): the risk heatmap colormap is a
 * measurement scale, so it must not flip between light and dark.
 */
export const RAW = {
${rawEntries.join(',\n')}
} as const

/** CSS custom property reference for a token, e.g. \`var(--accent)\`. */
export function cssVar(token: ColorToken): string {
  return \`var(--\${token})\`
}
`
}

/** Tokens still carrying an invented value, as "name/mode" pairs. */
function provisional({ modes, tokens }) {
  const pending = []
  for (const [name, token] of Object.entries(tokens)) {
    for (const mode of modes) {
      if (token.source?.[mode] === 'provisional') pending.push(`${name}/${mode}`)
    }
  }
  return pending
}

const source = readSource()
mkdirSync(OUT_DIR, { recursive: true })
writeFileSync(join(OUT_DIR, 'tokens.css'), buildCss(source), 'utf-8')
writeFileSync(join(OUT_DIR, 'tokens.ts'), buildTs(source), 'utf-8')

const count = Object.keys(source.tokens).length
console.log(`tokens: wrote ${String(count)} tokens x ${String(source.modes.length)} modes`)

// Loud rather than buried in JSON: these are placeholders, not the design.
const pending = provisional(source)
if (pending.length > 0) {
  console.log(`tokens: ${String(pending.length)} value(s) still provisional:`)
  for (const entry of pending) console.log(`  - ${entry}`)
}
