/**
 * Generates React icon components from the Figma-exported SVGs.
 *
 *   src/renderer/src/icons/svg/*.svg   exact exported bytes, never hand-drawn
 *   src/renderer/src/icons/manifest.json  composition + viewBox per icon
 *   src/renderer/src/icons/generated.tsx  <- written by this script
 *
 * Every fill and stroke becomes currentColor, so an icon takes its colour
 * from whatever themed container it sits in. Run with `pnpm run icons:build`.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const ICON_DIR = join(root, 'src', 'renderer', 'src', 'icons')
const SVG_DIR = join(ICON_DIR, 'svg')

const BANNER = `/* GENERATED by scripts/build-icons.mjs from ./svg + ./manifest.json. Do not edit. */`

/** Pull the drawable children out of an <svg> wrapper. */
function innerMarkup(svg) {
  const opening = svg.indexOf('>', svg.indexOf('<svg'))
  const closing = svg.lastIndexOf('</svg>')
  if (opening === -1 || closing === -1) throw new Error('Not an <svg> document')
  return svg.slice(opening + 1, closing).trim()
}

/**
 * Figma bakes the light-mode literal into every exported path. Swapping to
 * currentColor is what makes one component work in both themes.
 * `fill="none"` is load-bearing on stroked icons and must survive.
 */
function recolour(markup) {
  return markup
    .replace(/fill="#[0-9a-fA-F]{3,8}"/g, 'fill="currentColor"')
    .replace(/stroke="#[0-9a-fA-F]{3,8}"/g, 'stroke="currentColor"')
}

/** JSX needs camelCase attributes and self-closed tags. */
function toJsx(markup) {
  return markup
    .replace(/([a-z]+)-([a-z])/g, (match, head, next) => {
      // Only rewrite SVG presentation attributes, never path data.
      if (!/^(stroke|fill|clip|stop|font|text|marker|vector)$/.test(head)) return match
      return `${head}${next.toUpperCase()}`
    })
    .replace(/\sid="[^"]*"/g, '')
    .replace(/<(path|circle|rect|line|polygon|polyline|ellipse)([^>]*?)\/?>/g, '<$1$2 />')
    .replace(/\s+\/>/g, ' />')
}

function partMarkup(part) {
  const raw = readFileSync(join(SVG_DIR, part.file), 'utf-8')
  const body = toJsx(recolour(innerMarkup(raw)))

  // Figma applies some transforms on the component wrapper rather than baking
  // them into the exported vector, so the raw asset can be mirrored or
  // rotated relative to what the design shows. `transform` restores those.
  const transforms = []
  if (part.x !== undefined || part.y !== undefined) {
    transforms.push(`translate(${String(part.x ?? 0)} ${String(part.y ?? 0)})`)
  }
  if (part.transform !== undefined) transforms.push(part.transform)

  if (transforms.length === 0) return body
  return `<g transform="${transforms.join(' ')}">${body}</g>`
}

function buildComponent(icon) {
  const body = icon.parts.map(partMarkup).join('\n      ')
  return `/** Figma ${icon.figmaNode}. */
export function ${icon.name}Icon({ size = 16, ...props }: IconProps): ReactElement {
  return (
    <svg
      viewBox="${icon.viewBox}"
      height={size}
      width="auto"
      fill="none"
      focusable="false"
      aria-hidden={props['aria-label'] === undefined}
      {...props}
    >
      ${body}
    </svg>
  )
}`
}

const manifest = JSON.parse(readFileSync(join(ICON_DIR, 'manifest.json'), 'utf-8'))

const header = `${BANNER}

import type { ReactElement, SVGProps } from 'react'

export interface IconProps extends Omit<SVGProps<SVGSVGElement>, 'width' | 'height'> {
  /**
   * Rendered height in px; width follows from the icon's own aspect ratio.
   * Several of these are deliberately not square, so height is the honest
   * dimension to drive.
   */
  size?: number
}
`

const components = manifest.icons.map(buildComponent).join('\n\n')
const names = manifest.icons.map((icon) => `${icon.name}Icon`)

// The registry lives in its own module on purpose: a .tsx file that exports
// both components and a constant breaks React Fast Refresh.
const registry = `${BANNER}

import {
${names.map((name) => `  ${name}`).join(',\n')}
} from './generated'

/** Every icon, for gallery and story enumeration. */
export const ICONS = {
${names.map((name) => `  ${name}`).join(',\n')}
} as const

export type IconName = keyof typeof ICONS
`

writeFileSync(join(ICON_DIR, 'generated.tsx'), `${header}\n${components}\n`, 'utf-8')
writeFileSync(join(ICON_DIR, 'registry.ts'), registry, 'utf-8')
console.log(`icons: wrote ${String(manifest.icons.length)} components`)
