/**
 * Regenerate openapi.json from a local py-beacon checkout.
 *
 * py-beacon owns the spec; this repo commits a copy so the client can be
 * generated without python, a network, or a py-beacon install. Its exporter
 * already sorts keys and adds a trailing newline precisely so the file diffs
 * cleanly here.
 *
 *   pnpm run spec:refresh
 *
 * Set BEACON_PY_REPO to point at the checkout if it is not a sibling.
 */

import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const OUTPUT = join(root, 'openapi.json')
const VERSION_FILE = join(root, 'src', 'shared', 'apiVersion.ts')

const WINDOWS = process.platform === 'win32'

function findRepo() {
  const override = process.env.BEACON_PY_REPO
  const candidates = override
    ? [override]
    : [resolve(root, '..', 'py-beacon'), resolve(root, '..', 'py_beacon')]

  for (const candidate of candidates) {
    if (existsSync(join(candidate, 'scripts', 'export_openapi.py'))) return candidate
  }

  throw new Error(
    `No py-beacon checkout found. Looked in:\n  ${candidates.join('\n  ')}\n` +
      'Set BEACON_PY_REPO to its path.'
  )
}

/**
 * The venv interpreter, not PATH python. py-beacon's server extra (fastapi,
 * scipy, reportlab) lives in its venv; a PATH python would fail at import.
 */
function findPython(repo) {
  const venv = WINDOWS
    ? join(repo, '.venv', 'Scripts', 'python.exe')
    : join(repo, '.venv', 'bin', 'python')

  if (existsSync(venv)) return venv
  return WINDOWS ? 'python.exe' : 'python3'
}

const repo = findRepo()
const python = findPython(repo)

console.log(`py-beacon: ${repo}`)
console.log(`python:    ${python}`)

execFileSync(python, [join('scripts', 'export_openapi.py'), OUTPUT], {
  cwd: repo,
  stdio: 'inherit'
})

// Pin the version the client was generated against. The runtime check
// compares this with what /health reports, which catches running a newer
// server than the client knows about — something no CI check can see.
const spec = JSON.parse(readFileSync(OUTPUT, 'utf-8'))
const version = spec.info.version

writeFileSync(
  VERSION_FILE,
  `/* GENERATED by scripts/refresh-spec.mjs. Do not edit. */

/** py-beacon version this client's types were generated against. */
export const GENERATED_AGAINST = '${version}'
`,
  'utf-8'
)

console.log(`Pinned py-beacon ${version} in src/shared/apiVersion.ts`)
