/* GENERATED by scripts/build-tokens.mjs from tokens/colors.json. Do not edit. */

export type ThemeMode = 'light' | 'dark'

export type ColorToken =
  | 'canvas'
  | 'surface'
  | 'border'
  | 'divider'
  | 'text-primary'
  | 'text-secondary'
  | 'text-muted'
  | 'accent'
  | 'chrome-icon'
  | 'success'
  | 'danger'
  | 'sidebar-active-bg'
  | 'chrome-border'
  | 'chrome-search-bg'
  | 'chrome-search-stroke'
  | 'series-2'
  | 'series-3'

/**
 * Resolved literals per mode. Chart libraries paint to canvas and cannot read
 * CSS custom properties, so they need the value rather than a var() reference.
 * Components must use var(--token) instead of reaching in here.
 */
export const COLORS: Record<ThemeMode, Record<ColorToken, string>> = {
  light: {
    'canvas': '#f5ede0',
    'surface': '#fbf3e233',
    'border': '#ddd2b8',
    'divider': '#e8dfc9',
    'text-primary': '#2a2419',
    'text-secondary': '#6b6455',
    'text-muted': '#8b8577',
    'accent': '#4a88c7',
    'chrome-icon': '#62513c',
    'success': '#4c8a5e',
    'danger': '#c05c4e',
    'sidebar-active-bg': '#e5dcc6',
    'chrome-border': '#ddd2b8',
    'chrome-search-bg': '#b1997d33',
    'chrome-search-stroke': '#b1997d',
    'series-2': '#8b5cd6',
    'series-3': '#a86a12'
  },
  dark: {
    'canvas': '#1a1712',
    'surface': '#2a241933',
    'border': '#3d362a',
    'divider': '#332d23',
    'text-primary': '#f0e9dc',
    'text-secondary': '#a8a08f',
    'text-muted': '#7d766a',
    'accent': '#6ba6df',
    'chrome-icon': '#b5a894',
    'success': '#6fbf8a',
    'danger': '#e08277',
    'sidebar-active-bg': '#2f2a20',
    'chrome-border': '#3d362a',
    'chrome-search-bg': '#b1997d1f',
    'chrome-search-stroke': '#6b5c47',
    'series-2': '#c98bdb',
    'series-3': '#e8a33d'
  }
}

/**
 * Mode-independent by approval (taxonomy 9): the risk heatmap colormap is a
 * measurement scale, so it must not flip between light and dark.
 */
export const RAW = {
  heatmapLow: '#4ca56b',
  heatmapMid: '#d9b34c',
  heatmapHigh: '#ca5851'
} as const

/** CSS custom property reference for a token, e.g. `var(--accent)`. */
export function cssVar(token: ColorToken): string {
  return `var(--${token})`
}
