/* GENERATED by scripts/build-tokens.mjs from tokens/colors.json. Do not edit. */

export type ThemeMode = 'light' | 'dark'

export type ColorToken =
  | 'canvas'
  | 'surface'
  | 'border'
  | 'divider'
  | 'text-primary'
  | 'text-secondary'
  | 'text-muted'
  | 'accent'
  | 'success'
  | 'danger'
  | 'sidebar-active-bg'
  | 'chrome-border'
  | 'chrome-search-bg'
  | 'chrome-search-stroke'
  | 'series-2'
  | 'series-3'

/**
 * Resolved literals per mode. Chart libraries paint to canvas and cannot read
 * CSS custom properties, so they need the value rather than a var() reference.
 * Components must use var(--token) instead of reaching in here.
 */
export const COLORS: Record<ThemeMode, Record<ColorToken, string>> = {
  light: {
    canvas: '#f7f8f9',
    surface: '#ffffff',
    border: '#d8dcdf',
    divider: '#e7eaec',
    'text-primary': '#16181a',
    'text-secondary': '#4d5359',
    'text-muted': '#8b9198',
    accent: '#1f6feb',
    success: '#1a7f5a',
    danger: '#c0392b',
    'sidebar-active-bg': '#e8f0fe',
    'chrome-border': '#d8dcdf',
    'chrome-search-bg': '#ffffff',
    'chrome-search-stroke': '#cdd2d6',
    'series-2': '#8b5cd6',
    'series-3': '#a86a12'
  },
  dark: {
    canvas: '#101112',
    surface: '#17191b',
    border: '#2a2d30',
    divider: '#232629',
    'text-primary': '#e6e7e8',
    'text-secondary': '#a1a6ab',
    'text-muted': '#6f757b',
    accent: '#4a9eff',
    success: '#4ec9a0',
    danger: '#e0645e',
    'sidebar-active-bg': '#1d2733',
    'chrome-border': '#2a2d30',
    'chrome-search-bg': '#1a1d1f',
    'chrome-search-stroke': '#2f3336',
    'series-2': '#c98bdb',
    'series-3': '#e8a33d'
  }
}

/**
 * Mode-independent by approval (taxonomy 9): the risk heatmap colormap is a
 * measurement scale, so it must not flip between light and dark.
 */
export const RAW = {
  heatmapLow: '#4ca56b',
  heatmapMid: '#d9b34c',
  heatmapHigh: '#ca5851'
} as const

/** CSS custom property reference for a token, e.g. `var(--accent)`. */
export function cssVar(token: ColorToken): string {
  return `var(--${token})`
}
